// Generated by gencpp from file HDMap/msg_map_cmd.msg
// DO NOT EDIT!


#ifndef HDMAP_MESSAGE_MSG_MAP_CMD_H
#define HDMAP_MESSAGE_MSG_MAP_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace HDMap
{
template <class ContainerAllocator>
struct msg_map_cmd_
{
  typedef msg_map_cmd_<ContainerAllocator> Type;

  msg_map_cmd_()
    : header()
    , cmd()
    , argv1(0)
    , argv2(0)  {
    }
  msg_map_cmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cmd(_alloc)
    , argv1(0)
    , argv2(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type;
  _cmd_type cmd;

   typedef int32_t _argv1_type;
  _argv1_type argv1;

   typedef int32_t _argv2_type;
  _argv2_type argv2;





  typedef boost::shared_ptr< ::HDMap::msg_map_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::HDMap::msg_map_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct msg_map_cmd_

typedef ::HDMap::msg_map_cmd_<std::allocator<void> > msg_map_cmd;

typedef boost::shared_ptr< ::HDMap::msg_map_cmd > msg_map_cmdPtr;
typedef boost::shared_ptr< ::HDMap::msg_map_cmd const> msg_map_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::HDMap::msg_map_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::HDMap::msg_map_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace HDMap

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'HDMap': ['/media/vincent/DATA/Ubuntu/Project/catkin_ws/src/HDMap/msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::msg_map_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::msg_map_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::msg_map_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::msg_map_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::msg_map_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::msg_map_cmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::HDMap::msg_map_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f00b266a10ef2b0c602298f6b3a6d20";
  }

  static const char* value(const ::HDMap::msg_map_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f00b266a10ef2b0ULL;
  static const uint64_t static_value2 = 0xc602298f6b3a6d20ULL;
};

template<class ContainerAllocator>
struct DataType< ::HDMap::msg_map_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "HDMap/msg_map_cmd";
  }

  static const char* value(const ::HDMap::msg_map_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::HDMap::msg_map_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string cmd\n\
int32 argv1\n\
int32 argv2\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::HDMap::msg_map_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::HDMap::msg_map_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cmd);
      stream.next(m.argv1);
      stream.next(m.argv2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_map_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::HDMap::msg_map_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::HDMap::msg_map_cmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd);
    s << indent << "argv1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.argv1);
    s << indent << "argv2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.argv2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_MESSAGE_MSG_MAP_CMD_H
