// Generated by gencpp from file HDMap/msg_signal_list.msg
// DO NOT EDIT!


#ifndef HDMAP_MESSAGE_MSG_SIGNAL_LIST_H
#define HDMAP_MESSAGE_MSG_SIGNAL_LIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <HDMap/msg_signal.h>

namespace HDMap
{
template <class ContainerAllocator>
struct msg_signal_list_
{
  typedef msg_signal_list_<ContainerAllocator> Type;

  msg_signal_list_()
    : header()
    , signal_list()  {
    }
  msg_signal_list_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , signal_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::HDMap::msg_signal_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::HDMap::msg_signal_<ContainerAllocator> >::other >  _signal_list_type;
  _signal_list_type signal_list;





  typedef boost::shared_ptr< ::HDMap::msg_signal_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::HDMap::msg_signal_list_<ContainerAllocator> const> ConstPtr;

}; // struct msg_signal_list_

typedef ::HDMap::msg_signal_list_<std::allocator<void> > msg_signal_list;

typedef boost::shared_ptr< ::HDMap::msg_signal_list > msg_signal_listPtr;
typedef boost::shared_ptr< ::HDMap::msg_signal_list const> msg_signal_listConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::HDMap::msg_signal_list_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::HDMap::msg_signal_list_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace HDMap

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'HDMap': ['/media/vincent/DATA/Ubuntu/Project/catkin_ws/src/HDMap/msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::msg_signal_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::msg_signal_list_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::msg_signal_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::msg_signal_list_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::msg_signal_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::msg_signal_list_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::HDMap::msg_signal_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f17c4fa392d4f52230514eaf13b64431";
  }

  static const char* value(const ::HDMap::msg_signal_list_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf17c4fa392d4f522ULL;
  static const uint64_t static_value2 = 0x30514eaf13b64431ULL;
};

template<class ContainerAllocator>
struct DataType< ::HDMap::msg_signal_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "HDMap/msg_signal_list";
  }

  static const char* value(const ::HDMap::msg_signal_list_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::HDMap::msg_signal_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
HDMap/msg_signal[] signal_list\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: HDMap/msg_signal\n\
Header header\n\
string type\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 theta\n\
bool vertical\n\
string shape\n\
bool left\n\
bool forward\n\
bool right\n\
";
  }

  static const char* value(const ::HDMap::msg_signal_list_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::HDMap::msg_signal_list_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.signal_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_signal_list_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::HDMap::msg_signal_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::HDMap::msg_signal_list_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "signal_list[]" << std::endl;
    for (size_t i = 0; i < v.signal_list.size(); ++i)
    {
      s << indent << "  signal_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::HDMap::msg_signal_<ContainerAllocator> >::stream(s, indent + "    ", v.signal_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_MESSAGE_MSG_SIGNAL_LIST_H
