// Generated by gencpp from file HDMap/msg_route_info.msg
// DO NOT EDIT!


#ifndef HDMAP_MESSAGE_MSG_ROUTE_INFO_H
#define HDMAP_MESSAGE_MSG_ROUTE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace HDMap
{
template <class ContainerAllocator>
struct msg_route_info_
{
  typedef msg_route_info_<ContainerAllocator> Type;

  msg_route_info_()
    : route_id()
    , route_pose()  {
    }
  msg_route_info_(const ContainerAllocator& _alloc)
    : route_id(_alloc)
    , route_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _route_id_type;
  _route_id_type route_id;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _route_pose_type;
  _route_pose_type route_pose;





  typedef boost::shared_ptr< ::HDMap::msg_route_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::HDMap::msg_route_info_<ContainerAllocator> const> ConstPtr;

}; // struct msg_route_info_

typedef ::HDMap::msg_route_info_<std::allocator<void> > msg_route_info;

typedef boost::shared_ptr< ::HDMap::msg_route_info > msg_route_infoPtr;
typedef boost::shared_ptr< ::HDMap::msg_route_info const> msg_route_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::HDMap::msg_route_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::HDMap::msg_route_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace HDMap

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'HDMap': ['/home/iceytan/CLionProjects/HDMap/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::msg_route_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::msg_route_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::msg_route_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::msg_route_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::msg_route_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::msg_route_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::HDMap::msg_route_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9b44231877235db9b5919dbd913380f";
  }

  static const char* value(const ::HDMap::msg_route_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9b44231877235dbULL;
  static const uint64_t static_value2 = 0x9b5919dbd913380fULL;
};

template<class ContainerAllocator>
struct DataType< ::HDMap::msg_route_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "HDMap/msg_route_info";
  }

  static const char* value(const ::HDMap::msg_route_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::HDMap::msg_route_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] route_id\n\
float64[] route_pose\n\
";
  }

  static const char* value(const ::HDMap::msg_route_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::HDMap::msg_route_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.route_id);
      stream.next(m.route_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_route_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::HDMap::msg_route_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::HDMap::msg_route_info_<ContainerAllocator>& v)
  {
    s << indent << "route_id[]" << std::endl;
    for (size_t i = 0; i < v.route_id.size(); ++i)
    {
      s << indent << "  route_id[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.route_id[i]);
    }
    s << indent << "route_pose[]" << std::endl;
    for (size_t i = 0; i < v.route_pose.size(); ++i)
    {
      s << indent << "  route_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.route_pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_MESSAGE_MSG_ROUTE_INFO_H
