// Generated by gencpp from file HDMap/srv_map_dataResponse.msg
// DO NOT EDIT!


#ifndef HDMAP_MESSAGE_SRV_MAP_DATARESPONSE_H
#define HDMAP_MESSAGE_SRV_MAP_DATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace HDMap
{
template <class ContainerAllocator>
struct srv_map_dataResponse_
{
  typedef srv_map_dataResponse_<ContainerAllocator> Type;

  srv_map_dataResponse_()
    : res()  {
    }
  srv_map_dataResponse_(const ContainerAllocator& _alloc)
    : res(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::HDMap::srv_map_dataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::HDMap::srv_map_dataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srv_map_dataResponse_

typedef ::HDMap::srv_map_dataResponse_<std::allocator<void> > srv_map_dataResponse;

typedef boost::shared_ptr< ::HDMap::srv_map_dataResponse > srv_map_dataResponsePtr;
typedef boost::shared_ptr< ::HDMap::srv_map_dataResponse const> srv_map_dataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::HDMap::srv_map_dataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::HDMap::srv_map_dataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace HDMap

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'HDMap': ['/home/iceytan/CLionProjects/HDMap/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::srv_map_dataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::srv_map_dataResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::srv_map_dataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::srv_map_dataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::srv_map_dataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::srv_map_dataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::HDMap::srv_map_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53af918a2a4a2a182c184142fff49b0c";
  }

  static const char* value(const ::HDMap::srv_map_dataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53af918a2a4a2a18ULL;
  static const uint64_t static_value2 = 0x2c184142fff49b0cULL;
};

template<class ContainerAllocator>
struct DataType< ::HDMap::srv_map_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "HDMap/srv_map_dataResponse";
  }

  static const char* value(const ::HDMap::srv_map_dataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::HDMap::srv_map_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string res\n\
";
  }

  static const char* value(const ::HDMap::srv_map_dataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::HDMap::srv_map_dataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv_map_dataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::HDMap::srv_map_dataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::HDMap::srv_map_dataResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_MESSAGE_SRV_MAP_DATARESPONSE_H
