// Generated by gencpp from file HDMap/srv_map_cmdResponse.msg
// DO NOT EDIT!


#ifndef HDMAP_MESSAGE_SRV_MAP_CMDRESPONSE_H
#define HDMAP_MESSAGE_SRV_MAP_CMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace HDMap
{
template <class ContainerAllocator>
struct srv_map_cmdResponse_
{
  typedef srv_map_cmdResponse_<ContainerAllocator> Type;

  srv_map_cmdResponse_()
    : suss(false)  {
    }
  srv_map_cmdResponse_(const ContainerAllocator& _alloc)
    : suss(false)  {
  (void)_alloc;
    }



   typedef uint8_t _suss_type;
  _suss_type suss;





  typedef boost::shared_ptr< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srv_map_cmdResponse_

typedef ::HDMap::srv_map_cmdResponse_<std::allocator<void> > srv_map_cmdResponse;

typedef boost::shared_ptr< ::HDMap::srv_map_cmdResponse > srv_map_cmdResponsePtr;
typedef boost::shared_ptr< ::HDMap::srv_map_cmdResponse const> srv_map_cmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::HDMap::srv_map_cmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace HDMap

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'HDMap': ['/home/iceytan/CLionProjects/HDMap/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34610198ef7faf8dc35bc1abef48900b";
  }

  static const char* value(const ::HDMap::srv_map_cmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34610198ef7faf8dULL;
  static const uint64_t static_value2 = 0xc35bc1abef48900bULL;
};

template<class ContainerAllocator>
struct DataType< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "HDMap/srv_map_cmdResponse";
  }

  static const char* value(const ::HDMap::srv_map_cmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool suss\n\
";
  }

  static const char* value(const ::HDMap::srv_map_cmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.suss);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv_map_cmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::HDMap::srv_map_cmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::HDMap::srv_map_cmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "suss: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.suss);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_MESSAGE_SRV_MAP_CMDRESPONSE_H
