// Generated by gencpp from file HDMap/srv_map_cmd.msg
// DO NOT EDIT!


#ifndef HDMAP_MESSAGE_SRV_MAP_CMD_H
#define HDMAP_MESSAGE_SRV_MAP_CMD_H

#include <ros/service_traits.h>


#include <HDMap/srv_map_cmdRequest.h>
#include <HDMap/srv_map_cmdResponse.h>


namespace HDMap
{

struct srv_map_cmd
{

typedef srv_map_cmdRequest Request;
typedef srv_map_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_map_cmd
} // namespace HDMap


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::HDMap::srv_map_cmd > {
  static const char* value()
  {
    return "b616eb18e77140742b002119560b88f1";
  }

  static const char* value(const ::HDMap::srv_map_cmd&) { return value(); }
};

template<>
struct DataType< ::HDMap::srv_map_cmd > {
  static const char* value()
  {
    return "HDMap/srv_map_cmd";
  }

  static const char* value(const ::HDMap::srv_map_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::HDMap::srv_map_cmdRequest> should match 
// service_traits::MD5Sum< ::HDMap::srv_map_cmd > 
template<>
struct MD5Sum< ::HDMap::srv_map_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::HDMap::srv_map_cmd >::value();
  }
  static const char* value(const ::HDMap::srv_map_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::HDMap::srv_map_cmdRequest> should match 
// service_traits::DataType< ::HDMap::srv_map_cmd > 
template<>
struct DataType< ::HDMap::srv_map_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::HDMap::srv_map_cmd >::value();
  }
  static const char* value(const ::HDMap::srv_map_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::HDMap::srv_map_cmdResponse> should match 
// service_traits::MD5Sum< ::HDMap::srv_map_cmd > 
template<>
struct MD5Sum< ::HDMap::srv_map_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::HDMap::srv_map_cmd >::value();
  }
  static const char* value(const ::HDMap::srv_map_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::HDMap::srv_map_cmdResponse> should match 
// service_traits::DataType< ::HDMap::srv_map_cmd > 
template<>
struct DataType< ::HDMap::srv_map_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::HDMap::srv_map_cmd >::value();
  }
  static const char* value(const ::HDMap::srv_map_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HDMAP_MESSAGE_SRV_MAP_CMD_H
