// Generated by gencpp from file HDMap/LocalMap.msg
// DO NOT EDIT!


#ifndef HDMAP_MESSAGE_LOCALMAP_H
#define HDMAP_MESSAGE_LOCALMAP_H

#include <ros/service_traits.h>


#include "LocalMapRequest.h"
#include "LocalMapResponse.h"


namespace HDMap
{

struct LocalMap
{

typedef LocalMapRequest Request;
typedef LocalMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocalMap
} // namespace HDMap


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::HDMap::LocalMap > {
  static const char* value()
  {
    return "9b95e06638142dcc7cd09553930c341b";
  }

  static const char* value(const ::HDMap::LocalMap&) { return value(); }
};

template<>
struct DataType< ::HDMap::LocalMap > {
  static const char* value()
  {
    return "HDMap/LocalMap";
  }

  static const char* value(const ::HDMap::LocalMap&) { return value(); }
};


// service_traits::MD5Sum< ::HDMap::LocalMapRequest> should match 
// service_traits::MD5Sum< ::HDMap::LocalMap > 
template<>
struct MD5Sum< ::HDMap::LocalMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::HDMap::LocalMap >::value();
  }
  static const char* value(const ::HDMap::LocalMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::HDMap::LocalMapRequest> should match 
// service_traits::DataType< ::HDMap::LocalMap > 
template<>
struct DataType< ::HDMap::LocalMapRequest>
{
  static const char* value()
  {
    return DataType< ::HDMap::LocalMap >::value();
  }
  static const char* value(const ::HDMap::LocalMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::HDMap::LocalMapResponse> should match 
// service_traits::MD5Sum< ::HDMap::LocalMap > 
template<>
struct MD5Sum< ::HDMap::LocalMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::HDMap::LocalMap >::value();
  }
  static const char* value(const ::HDMap::LocalMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::HDMap::LocalMapResponse> should match 
// service_traits::DataType< ::HDMap::LocalMap > 
template<>
struct DataType< ::HDMap::LocalMapResponse>
{
  static const char* value()
  {
    return DataType< ::HDMap::LocalMap >::value();
  }
  static const char* value(const ::HDMap::LocalMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HDMAP_MESSAGE_LOCALMAP_H
