// Generated by gencpp from file HDMap/RoadMSG.msg
// DO NOT EDIT!


#ifndef HDMAP_MESSAGE_ROADMSG_H
#define HDMAP_MESSAGE_ROADMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include "Pose2DArray.h"

namespace HDMap
{
template <class ContainerAllocator>
struct RoadMSG_
{
  typedef RoadMSG_<ContainerAllocator> Type;

  RoadMSG_()
    : header()
    , lanes()  {
    }
  RoadMSG_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lanes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::HDMap::Pose2DArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::HDMap::Pose2DArray_<ContainerAllocator> >::other >  _lanes_type;
  _lanes_type lanes;





  typedef boost::shared_ptr< ::HDMap::RoadMSG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::HDMap::RoadMSG_<ContainerAllocator> const> ConstPtr;

}; // struct RoadMSG_

typedef ::HDMap::RoadMSG_<std::allocator<void> > RoadMSG;

typedef boost::shared_ptr< ::HDMap::RoadMSG > RoadMSGPtr;
typedef boost::shared_ptr< ::HDMap::RoadMSG const> RoadMSGConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::HDMap::RoadMSG_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::HDMap::RoadMSG_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace HDMap

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'HDMap': ['/media/vincent/DATA/Ubuntu/Project/catkin_ws/src/HDMap/msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::RoadMSG_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::HDMap::RoadMSG_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::RoadMSG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HDMap::RoadMSG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::RoadMSG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HDMap::RoadMSG_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::HDMap::RoadMSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "738b179fcc70ccab1d01013bdf414acf";
  }

  static const char* value(const ::HDMap::RoadMSG_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x738b179fcc70ccabULL;
  static const uint64_t static_value2 = 0x1d01013bdf414acfULL;
};

template<class ContainerAllocator>
struct DataType< ::HDMap::RoadMSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "HDMap/RoadMSG";
  }

  static const char* value(const ::HDMap::RoadMSG_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::HDMap::RoadMSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
HDMap/Pose2DArray[] lanes\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: HDMap/Pose2DArray\n\
Header header\n\
geometry_msgs/Pose2D[] lane\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::HDMap::RoadMSG_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::HDMap::RoadMSG_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lanes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoadMSG_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::HDMap::RoadMSG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::HDMap::RoadMSG_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lanes[]" << std::endl;
    for (size_t i = 0; i < v.lanes.size(); ++i)
    {
      s << indent << "  lanes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::HDMap::Pose2DArray_<ContainerAllocator> >::stream(s, indent + "    ", v.lanes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_MESSAGE_ROADMSG_H
